recipes/urls.py
from django.urls import path, re_path
from . import views


app_name='recipes'
urlpatterns = [
    path('', views.recipe_list_view, name='list'),
    path('search/', views.recipe_search_view, name='search'),
    path('create/', views.recipe_create_view, name='create'),
    path('<slug:slug>/', views.recipe_detail_view, name='detail'),
]

recipes/models.py
from django.conf import settings
from django.db import models
from django.utils.text import slugify
from .validators import validate_unit_of_measure

# Create your models here.
class Recipe(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default='1',)
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=255, blank=True, null=True)
    ingredients = models.TextField(blank=True, null=True,)
    directions = models.TextField(blank=True, null=True,)
    timestamp = models.DateTimeField(auto_now_add=True) # automatically input time when record is created
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField()
    thumb = models.ImageField(default='default.png', blank=True)

    
    def __str__(self):
        return self.title
    
    def snippet(self):
        return self.description[:50] + '...'

recipes/forms.py
from django.forms import ModelForm
from django import forms
from .models import Recipe


class CreateRecipeForm(ModelForm):
    title = forms.CharField()
    description = forms.CharField()
    ingredients = forms.Textarea()
    directions = forms.Textarea()
    slug = forms.CharField()
    thumb = forms.ImageField()

    class Meta:
        model = Recipe
        fields = ['title', 'description', 'ingredients', 'directions', 'slug', 'thumb']

recipes/views.py
from django.shortcuts import render, redirect               # get_list_or_404,
from django.http import HttpResponse

from django.contrib.auth.decorators import login_required
from .models import Recipe
from . import forms

from .forms import CreateRecipeForm


# Create your views here.


def recipe_list_view(request):
    """
    View to display list of all recipes - will have to be limited in size eventaully 
    or paginated - don't know how to do that yet
    
    """
    recipes = Recipe.objects.all().order_by('title')   
    return render(request, 'recipes/recipe_list_view.html', {'recipes':recipes} )


def recipe_detail_view(request, slug):
    """
    View to display individual recipe based on the slug value
    
    """
    recipe = Recipe.objects.get(slug=slug)
    
    return render(request, 'recipes/recipe_detail_view.html', {'recipe':recipe } )


def recipe_search_view(request):
    """
    Function to search the database for recipes
    
    """

    # if search was made 
    print(request.method == "POST") 
    if request.method == "POST":
        
        query_name = request.POST.get('title', None)
        print(query_name)
        
        if query_name:
            recipes = Recipe.objects.filter(title__contains=query_name)
            print(recipes)
            return render(request, 'recipes/recipe_search_view.html', {'recipes':recipes})
        else:
            recipes = Recipe.objects.all().order_by('timestamp')
            return render(request, 'recipes/recipe_list_view.html', {'recipes':recipes})
    else:
        
        return render(request, 'recipes/recipe_search_view.html')


@login_required(login_url="/accounts/login/")
def recipe_create_view(request):
    """
    Function that is used to save a new recipe to the database
    Log is required for this 
    """
    if request.method == "POST":
        form = CreateRecipeForm(request.POST, request.FILES)
        if form.is_valid():
             form.save()

        return redirect('recipes:list')
    else:
        form = CreateRecipeForm()
    return render(request, 'recipes/recipe_create_view.html', {'form': form})

recipes/templates/recipes/recipe_create_ingredient_view.html
<h2> Create a New Recipe </h2>
        
        <form class='model-create-recipe-form' action={% url 'recipes:create_ingredient' %} method='post' enctype="multipart/form-data">
            {% csrf_token %}

           <p> Ingredient Name: {{ recipe_form.title }} </p>
           <p> Recipe Description:  {{ recipe_form.description }}</p>
           {% comment %} <p> Recipe Ingredients:  {{ recipe_form.ingredients }} </p> {% endcomment %}
           <p> Recipe Directions:  {{ recipe_form.directions }}</p>
           <p> Recipe Slug {{ recipe_form.slug }}</p>
           <p> Recipe Image {{ recipe_form.thumb }} </p>
            
            <input class='save-recipe' type='submit' value='Save Recipe'>
</form>

recipes/templates/recipes/recipe_create_view.html
{% extends 'base.html' %}

{% block content%}

    <div class='create-recipe' style='margin:30px; 10px; '>
        <h2> Create a New Recipe </h2>
        
        <form class='model-create-recipe-form' action"{% url 'recipes:create' %}" method='post' enctype="multipart/form-data">
            {% comment %} using form object to display model fields. {% endcomment %}
            {% csrf_token %}
            
            <p>Recipe Name: {{ form.title }} </p><br>
            <p> Description: {{ form.description }} </p><br>
            <p>Ingredients: {{ form.ingredients }} </p><br>
            <p>Directions: {{ form.directions }} </p><br>
            <p>Select File: {{ form.thumb }}</p> <br>
            <p>Enter Slug: {{ form.slug }}</p>

            <button type='submit' value=submit> Save Recipe </button>
        </form>
        <br>
    </div>
        <script src="/static/slugify.js"></script>


{% endblock %}

recipes/templates/recipes/recipe_detail_view.html
{% extends 'base.html' %}

{% block content %}

<div class='recipe-detail'>
    <div class='recipe'>
        {% comment %} display recipe fields for individual recipes {% endcomment %}

        {% comment %} need to figure out how to list instructions and ingredients one per line {% endcomment %}
        <img src="{{ recipe.thumb.url }}"/>
        <h2>{{ recipe.title }} </h2>
        <h4>{{ recipe.description }}</h4>
        <h5> {{ recipe.ingredients }} </h5>
        <h5> {{ recipe.directions }} </h5>
        <h6> {{ recipe.slug }} </h6>

        <h5> Submitted by:  {{ recipe.user }} </h5>
        
        <p>{{ recipe.date }} </p>


    </div>
</div>


{% endblock content %}

recipes/templates/recipes/recipe_list_view.html
{% extends 'base.html' %}

{% block content %}
    <h1>Recipe List</h1>
    
    <div class="recipes">
        {% for recipe in recipes %}
        <div class="recipe">
            <h2><a href="{% url 'recipes:detail' slug=recipe.slug %}">{{ recipe.title }}</a></h2>
            <p>{{ recipe.snippet }}</p>
            <p><img src="{{ recipe.thumb.url }}"/></p>
            <p>{{ recipe.timestamp }}</p>
            <p class='submitted-by'>Submitted by: {{ recipe.user }}</p>
        </div>
        {% endfor %}
    </div>
{% endblock content %}

recipes/templates/recipes/recipe_search_view.html
{% extends 'base.html' %}

{% block content %}

<div class='recipe-search'>
    <div class='recipe'>
        
            <h1>Search Results</h1>
            {% for recipe in recipes %}
                <div class="recipe">
                    <h2><a href="{% url 'recipes:detail' slug=recipe.slug %}">{{ recipe.title }}</a></h2>
                    <p>{{ recipe.snippet }}</p>
                    <p><img src="{{ recipe.thumb.url }}"/></p>
                    <p>{{ recipe.timestamp }}</p>
                    <p class='submitted-by'>Submitted by: {{ recipe.user }}</p>
                </div>
            {% endfor %}

        <div class="recipes">
        
    </div>


    </div>
</div>


{% endblock content %}