accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'

urlpatterns = [
    url('signup/', views.signup_view, name='signup'),
    url('login/', views.login_view, name='login'),
    url('logout/', views.logout_view, name='logout')
]

recipe_box_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from . import views
from recipes import views as recipe_views




urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('recipes/', include('recipes.urls', namespace='recipes')),    #import from the recipe app
    path('about/', views.about_view),
    path('admin/', admin.site.urls),
    path('', recipe_views.recipe_list_view, name='home'),
]

urlpatterns += staticfiles_urlpatterns()    # works in debug mode
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path, re_path
from . import views


app_name='recipes'
urlpatterns = [
    path('', views.recipe_list_view, name='list'),
    path('search/', views.recipe_search_view, name='search'),
    path('create/', views.recipe_create_view, name='create'),
    path('<slug:slug>/', views.recipe_detail_view, name='detail'),
]

accounts/models.py
from django.db import models

# Create your models here.

recipes/models.py
from django.conf import settings
from django.db import models
from django.utils.text import slugify
from .validators import validate_unit_of_measure

# Create your models here.
class Recipe(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default='1',)
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=255, blank=True, null=True)
    ingredients = models.TextField(blank=True, null=True,)
    directions = models.TextField(blank=True, null=True,)
    timestamp = models.DateTimeField(auto_now_add=True) # automatically input time when record is created
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField()
    thumb = models.ImageField(default='default.png', blank=True)

    
    def __str__(self):
        return self.title
    
    def snippet(self):
        return self.description[:50] + '...'

recipes/forms.py
from django.forms import ModelForm
from django import forms
from .models import Recipe


class CreateRecipeForm(ModelForm):
    title = forms.CharField()
    description = forms.CharField()
    ingredients = forms.Textarea()
    directions = forms.Textarea()
    slug = forms.CharField()
    thumb = forms.ImageField()

    class Meta:
        model = Recipe
        fields = ['title', 'description', 'ingredients', 'directions', 'slug', 'thumb']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def signup_view(request):
    
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # log user in 
            login(request, user)
            return redirect('recipes:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form':form})



def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        print(dir(form))
        if form.is_valid():
            # print(dir(form))
            # login the user
            user = form.get_user()
            login(request, user)
            # if the user came from the recipes/create page
            # redirect them back to that page after they login
            # otherwise redirect them to the list of recipes
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('recipes:list') # don't want this     
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form':form })


def logout_view(request):
    if request.method == 'POST':
        logout(request)
    
    return redirect('recipes:list')

recipe_box_project/views.py
"""
Purpose: Render HTML web pages
"""
from django.http import HttpResponse
from django.shortcuts import render

def home_view(request):
    # return HttpResponse('home_view')
    return render(request, 'home_page.html')


def about_view(request):
    return HttpResponse('about_view')

recipes/views.py
from django.shortcuts import render, redirect               # get_list_or_404,
from django.http import HttpResponse

from django.contrib.auth.decorators import login_required
from .models import Recipe
from . import forms

from .forms import CreateRecipeForm


# Create your views here.


def recipe_list_view(request):
    """
    View to display list of all recipes - will have to be limited in size eventaully 
    or paginated - don't know how to do that yet
    
    """
    recipes = Recipe.objects.all().order_by('title')   
    return render(request, 'recipes/recipe_list_view.html', {'recipes':recipes} )


def recipe_detail_view(request, slug):
    """
    View to display individual recipe based on the slug value
    
    """
    recipe = Recipe.objects.get(slug=slug)
    
    return render(request, 'recipes/recipe_detail_view.html', {'recipe':recipe } )


def recipe_search_view(request):
    """
    Function to search the database for recipes
    
    """

    # if search was made 
    print(request.method == "POST") 
    if request.method == "POST":
        
        query_name = request.POST.get('title', None)
        print(query_name)
        
        if query_name:
            recipes = Recipe.objects.filter(title__contains=query_name)
            print(recipes)
            return render(request, 'recipes/recipe_search_view.html', {'recipes':recipes})
        else:
            recipes = Recipe.objects.all().order_by('timestamp')
            return render(request, 'recipes/recipe_list_view.html', {'recipes':recipes})
    else:
        
        return render(request, 'recipes/recipe_search_view.html')


@login_required(login_url="/accounts/login/")
def recipe_create_view(request):
    """
    Function that is used to save a new recipe to the database
    Log is required for this 
    """
    if request.method == "POST":
        form = CreateRecipeForm(request.POST, request.FILES)
        if form.is_valid():
             form.save()

        return redirect('recipes:list')
    else:
        form = CreateRecipeForm()
    return render(request, 'recipes/recipe_create_view.html', {'form': form})

templates/about.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>About Page</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
       <h1>This is the about page</h1>
       <p> My About Page </p>
        
        <script src="" async defer></script>
    </body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <title>The Recipe Box</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>

    <body>
        <header class="wrapper">
            {% comment %} Create Buttons that appear on each page {% endcomment %}

            <h1><a href="{% url 'home' %}"><img src="{% static 'logo2.png' %}" alt="The Recipe Box"/></a></h1>
            <nav>
                
                <form class='login-link' action="{% url 'accounts:login' %}" method='post'>
                    {% csrf_token %}
                    <button class='btn' type='submit'>Login</button>
                </form>
                <br>

                <form class='logout-link' action="{% url 'accounts:logout' %}" method='post'>
                    {% csrf_token %}
                    <button class='btn' type='submit'>Logout</button>
                </form>
                <br>

                <form class='create-recipe-link' action="{% url 'recipes:create' %}" method='post'>
                    {% csrf_token %}
                    
                    <button class='btn' type='submit'>Create Recipe</button>
                </form>
                <br>

                <form class='search-recipe-link' action={% url 'recipes:search' %} method='post' enctype="multipart/form-data">
                    {% csrf_token %}
                    <form class='query' action="{% url 'recipes:search' %}" method='post' >

                    <input type='text' name='title' placeholder="Search Recipes" />
                    <button class='btn' type='submit'>Search Recipes</button>
                </form>
            </nav>
            
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock content %}
        </div>

        <footer>       
        </footer>
    </body>


</html>

templates/home_page.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Home Page</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
       <h1>This is the home page</h1>
       <p> My Recipe Home Page </p>
        
        <script src="" async defer></script>
    </body>
</html>